version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:Almejo.Pass.%4069@host.docker.internal:5432/proyecto_ferkonsa
      - JWT_SECRET=clave_super_secreta
      - PORT=3000
