version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=2105.Satu
      - DB_NAME=proyecto_ferkonsa
  logistics-service:
    build: ./logistics-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=2105.Satu
      - DB_NAME=proyecto_ferkonsa
  
  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=2105.Satu
      - DB_NAME=proyecto_ferkonsa

  order-service:
    build: ./order-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=2105.Satu
      - DB_NAME=proyecto_ferkonsa